### ISSUE TITLE
(≠ (+ Spacemacs Gorilla) ❤️)

### ISSUE THREAD

**Issue by PEZ** [JonyEpsilon/gorilla-repl#237]
If I enable Gorilla for a project I can no longer run `lein repl`. It seems to be a clash with the [Spacemacs Clojure layer](https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/clojure) which needs this in `~/.lein/profiles.clj`:

```clojure
{:user {:plugins [[cider/cider-nrepl "0.10.0-SNAPSHOT"]
                  [refactor-nrepl "1.2.0-SNAPSHOT"]]
        :dependencies [[alembic "0.3.2"]
                       [org.clojure/tools.nrepl "0.2.12"]]}}
```

If I remove that stuff, `lein repl` starts. (I can also keep that stuff and run `lein repl` if I don't include the `lein-gorilla` plugin, but how fun is that?

How it crashes:

```
$ lein repl
Error loading refactor-nrepl.middleware: java.lang.RuntimeException: No such var: cljs/requires-piggieback, compiling:(refactor_nrepl/middleware.clj:134:2)
Exception in thread "main" java.lang.RuntimeException: Unable to resolve var: refactor-nrepl.middleware/wrap-refactor in this context, compiling:(/private/var/folders/xj/fvbl6w912bz_4c2vt9m514qw0000gn/T/form-init3568797876882083380.clj:1:6864)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6730)
	at clojure.lang.Compiler.analyze(Compiler.java:6524)
	at clojure.lang.Compiler.analyze(Compiler.java:6485)
	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3791)
	... snip! ...
Caused by: java.lang.RuntimeException: Unable to resolve var: refactor-nrepl.middleware/wrap-refactor in this context
	at clojure.lang.Util.runtimeException(Util.java:221)
	at clojure.lang.Compiler$TheVarExpr$Parser.parse(Compiler.java:698)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6723)
	... 34 more
```

**Comment by JonyEpsilon** [comment]
Argghhh. The endless problems of nREPL middleware! Fundamentally the difficulty is that nREPL wasn't really built to accommodate the rich variety of tooling that's grown up around it. Specifically, in this case I'm not really sure what the problem is, but will try and look into it. Thanks for the detailed report :-)
